#!/bin/bash

exec 2>&1 # fix stderr logging for daemontools

export PATH=/usr/bin:/usr/local/bin:$PATH
export NODE_ENV=production
export BROWSERID_FAKE_VERIFICATION=1
# export NODE_EXTRA_CONFIG=/...
export CONFIG_FILES="/vagrant/puppet/files/browserid/config/vagrant.json,/vagrant/puppet/secrets/browserid/swebhead/socketlabs.json"

cd /opt/browserid/
ulimit -n 8192
exec setuidgid browserid bin/dbwriter >> /var/browserid/log/dbwriter.log

sleep 5