#!/bin/bash

exec 2>&1 # fix stderr logging for daemontools

export PATH=/usr/bin:/usr/local/bin:$PATH
export NODE_ENV=production
# export NODE_EXTRA_CONFIG=/...
export CONFIG_FILES="/vagrant/puppet/files/browserid/config/vagrant.json"

cd /opt/browserid/
ulimit -n 8192
exec setuidgid browserid bin/proxy >> /var/browserid/log/proxy.log