#!/bin/bash

exec 2>&1 # fix stderr logging for daemontools

export PATH=/usr/bin:/usr/local/bin:$PATH
# export NODE_ENV=production
# export NODE_EXTRA_CONFIG=/...
export CONFIG_FILES="/home/browserid/browserid/config/local.json,/vagrant/puppet-webhead/files/browserid/config/vagrant.json"
export HOST=192.168.33.11
export IP_ADDRESS=192.168.33.11
export PORT=10007
export PUBLIC_URL=http://192.168.33.11:10002

cd /home/browserid/browserid/
ulimit -n 8192
exec setuidgid browserid bin/browserid