#!/bin/bash

exec 2>&1 # fix stderr logging for daemontools

export PATH=/usr/bin:/usr/local/bin:$PATH
export NODE_ENV=production
# export NODE_EXTRA_CONFIG=/...
export CONFIG_FILES="/home/browserid/browserid/config/local.json,/vagrant/puppet-dbwriter/files/browserid/config/vagrant.json"
export BROWSERID_FAKE_VERIFICATION=1

cd /home/browserid/browserid/
ulimit -n 8192
exec setuidgid browserid bin/dbwriter >> /home/browserid/browserid/var/log/dbwriter.log

sleep 5