#!/bin/bash

exec 2>&1 # fix stderr logging for daemontools

export PATH=/usr/bin:/usr/local/bin:$PATH
# export NODE_ENV=production
# export NODE_EXTRA_CONFIG=/...
export CONFIG_FILES="/opt/browserid/config/local.json"
export HOST=localhost
export IP_ADDRESS=192.168.33.11
export PORT=10001
export PUBLIC_URL=http://192.168.33.11
export VERIFIER_URL=http://192.168.33.11/verify

cd /opt/browserid/
ulimit -n 8192
exec setuidgid browserid scripts/serve_example.js > /opt/browserid/var/log/example.log